### ISSUE TITLE
curl error when uploading - "Please use the CURLFile class instead"

### ISSUE THREAD

**Issue by electblake** [teepluss/laravel4-cloudinary#2]
ErrorException

curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead

file: app/vendor/cloudinary/cloudinary_php/src/Uploader.php

line: 182

**Comment by teepluss** [comment]
Cloudinary uploader is a part of vendor, It' not my code.

**Comment by electblake** [comment]
OH - you're right ;)

I did the fix but I'll obviously submit to `cloudinary_php`
