### ISSUE TITLE
Cloudinary upload API deprecated

### ISSUE THREAD

**Issue by shuchita29** [teepluss/laravel4-cloudinary#7]
ErrorException

curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead in /var/www/webroot/UAT/admin/listings/src/Uploader.php on line 185

**Comment by teepluss** [comment]
I use official library from cloudinary "https://github.com/cloudinary/cloudinary_php/blob/master/src/Uploader.php"
